CREATE OR REPLACE TRIGGER TRG_EMPLOYEES_BUR
BEFORE UPDATE ON APP_TBL2
FOR EACH ROW
DECLARE
V_OPERATION VARCHAR2(20);
BEGIN

IF INSERTING THE
    V_OPERATION := 'INSERT';
ELSEIF UPDATING THEN
    V_OPERATION := 'UPDATE';
ELSE
    V_OPERATION := 'DELETE';
END IF;

END;