CREATE TABLE CUSTOMERS
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(20),
    CREDIT_LIMIT NUMBER
);

INSERT INTO CUSTOMER VALUES(100,'TOM JONES',2000);
INSERT INTO CUSTOMERS VALUES(101,'JOAN COLLINS',100);


EXEC DMS_FGA.ADD_POLICY
(
    OBJECT_SCHEMA => 'DBSEC',
    OBJECT_NAME => 'CUSTOMERS',
    POLICY_NAME =>'AUDIT_POLICY_1_SELECT',
    AUDIT_CONDITION => NULL,
    AUDIT_COLUMN => NULL,
    HANDLER_SCHEMA => NULL,
    HANDLER_MODULE => NULL,
    ENABLE => TRUE,
    STATEMENT_TYPES => 'SELECT'
)


EXEC DMS_FGA.ADD_POLICY
(
    OBJECT_SCHEMA => 'DBSEC',
    OBJECT_NAME => 'CUSTOMERS',
    POLICY_NAME =>'AUDIT_POLICY_2_CREDIT',
    AUDIT_CONDITION => 'CREDIT_LIMIT >= 10000',
    AUDIT_COLUMN => NULL,
    HANDLER_SCHEMA => NULL,
    HANDLER_MODULE => NULL,
    ENABLE => TRUE,
    STATEMENT_TYPES => 'INSERT, UPDATE'
)


EXEC DMS_FGA.ADD_POLICY
(
    OBJECT_SCHEMA => 'DBSEC',
    OBJECT_NAME => 'CUSTOMERS',
    POLICY_NAME =>'AUDIT_POLICY_3_DELETE',
    AUDIT_CONDITION => NULL,
    AUDIT_COLUMN => NULL,
    HANDLER_SCHEMA => NULL,
    HANDLER_MODULE => NULL,
    ENABLE => TRUE,
    STATEMENT_TYPES => 'DELETE'
)

SELECT OBJECT_NAME, POLICY_NAME, POLICY_TEXT,SEL,INS,DEL
FROM USER_AUDIT_POLICIES;

CONN SYS@SEC AS SYSDBA

AUDIT SELECT, INSERT, UPDATE, DELETE ON SYS.AUD$ BY ACCESS;

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS SET 
CREDIT_LIMIT = 110000
WHERE CUSTOMER_ID = 101

UPDATE CUSTOMERS SET
CREDIT_LIMIT = 5000
WHERE CUSTOMER_ID = 101

INSERT INTO CUSTOMERS VALUES(102,'Juan Perez','50000');


INSERT INTO CUSTOMERS VALUES(103,'Jhon Villarreal','2000');

DELETE CUSTOMERS WHERE CUSTOMER_ID= 103;

SELECT * FROM CUSTOMERS;

SELECT OBJECT_NAME, POLICY_NAME, SQL_TEXT,STATEMENT_TYPE
FROM DBA_FGA_AUDIT_TRAIL;