CREATE OR REPLACE TRIGGER TRG_BEFORE_ALTER
BEFORE ALTER ON DATABASE
BEGIN

    IF USER = 'PEDRO' THEN
     RAISE_APPLICATION_ERROR(-20000, 'YOU MAY NOT MODIFY STRUCTURE OF ANY TABLE');
    END IF;
END;
/

---------------------------------------------------


CREATE TABLE DEPARTMENTS2
(
    DEPARTMENT_ID NUMBER(2) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20),
    CITY VARCHAR2(30),
    STATE CHAR(2)
);


ALTER TABLE DEPARTMENTS2
    MODIFY DEPARTMENT_NAME VARCHAR2(60)
/

---------------------------------------------------