CREATE TABLE EMPLOYEES
( 
    EMPLOYEES_ID NUMBER,
    EMPLOYEES_NAME VARCHAR2(50)
);

CREATE OR REPLACE TRIGGER TRG_EMPLOYEES_AUDR
AFTER UPDATE OR DELETE ON EMPLOYEES
DECLARE
V_OPERATION VARCHAR2(20);
BEGIN
IF INSERTING THE
    V_OPERATION := 'INSERT';
ELSEIF UPDATING THEN
    V_OPERATION := 'UPDATE';
ELSE
    V_OPERATION := 'DELETE';
END IF;
END;
/