
CREATE TABLE DEPARTMENTS
(
    DEPARTMENT_ID NUMBER(2) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20),
    CITY VARCHAR2(30),
    STATE CHAR(2)
);

CREATE TABLE APP_AUDIT_DATA
(
    AUDIT_DATA_ID NUMBER PRIMARY KEY,
    AUDIT_OBJECT VARCHAR2(30),
    AUDIT_OPERATION VARCHAR(20),
    AUD_INS_DTTM DATE,
    AUD_UPD_USER VARCHAR2(30),
    AUD_REC_STAT VARCHAR2(1)
);

CREATE SEQUENCE SEQ_APP_AUDIT_DATA
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER;

DROP TRIGGER TRG_DEPARTMENT_AIUD;

CREATE OR REPLACE TRIGGER TRG_DEPARTMENT_AIUD
AFTER INSERT OR UPDATE OR DELETE
ON DEPARTMENTS
DECLARE
    V_OPR VARCHAR2(20);
BEGIN
    IF INSERTING THEN
        V_OPERATION:= 'INSERT';
    ELSIF UPDATING THEN
        V_OPERATION:= 'UPDATE';
    ELSE
        V_OPERATION:= 'DELETE';
    END IF;

    INSERT INTO APP_AUDIT_DATA(
        AUDIT_DATA_ID,
        AUDIT_OBJECT,
        AUDIT_OPERATION,
        AUD_INS_DTTM,
        AUD_UPD_USER,
        AUD_REC_STAT
    ) VALUES
    (
        SEQ_APP_AUDIT_DATA.NEXTVAL,
        'DEPARMENTS',
        V_OPR,
        SYSDATE,
        USER,
        'A'
    );
END;


INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,CITY,STATE)
VALUES(11,'ACCOUNTING','BOSTON','NV');


INSERT INTO DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,CITY,STATE)
VALUES(12,'production','redlands','CA');
COMMIT;

UPDATE DEPARTMENTS SET
CITY = 'DALLAS',
STATE = 'TX'
WHERE DEPARTMENT_ID = 10;

COMMIT;

DELETE FROM DEPARTMENTS WHERE DEPARMENT_ID=11;
COMMIT;

SELECT *
FROM APP_AUDIT_DATA;


